language: node_js
node_js:
  - 6.10.2
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
script:
  - grunt build
  - grunt test
services:
  - mongodb
  - redis
